export const themeNames = [
  'communication.breakdown',
  'dancing.days',
  'funky.drummer',
  'glass.onion',
  'hello.spaceboy',
  'kozmic.blues',
  'led.zeppelin',
  'strange.brew',
  'sweat.leaf',
  // 'big.payback',
  // 'boogie.wonderland',
  // 'celebration.day',
  // 'four.sticks',
  // 'howling.wolf',
  // 'jealous.again',
  // 'little.wing',
  // 'muddy.waters',
  // 'war.pigs',
]
