export const COLOR_0 = [
  'constant.character',
  'constant.language.boolean',
  'entity.name.tag.UNDERLINE',
  'keyword',
  'markup.italic',
  'punctuation.accessor.js',
  'punctuation.separator.key-value.js',
  'storage.modifier.js',
  'storage.type',
  'string.template',
  'support.constant',
  'support.function.dom.js',
  'support.variable.property.js',
  'variable.language.constructor.UNDERLINE',
  'variable.language.this',
]

export const COLOR_1 = [
  'constant.language.null.js',
  'entity.name.type',
  'entity.other.inherited-class',
  'markup.heading.markdown',
  'meta.brace.round.js',
  'entity.name.function.UNDERLINE',
  'meta.tag.attributes.js',
  'punctuation.accessor.js',
  'punctuation.separator.comma.js',
  'source.js',
  'storage.modifier.async.js',
  'support.class.builtin.js',
  'support.type.primitive.js',
  'support.variable.property.js',
  'variable',
  'variable.other.object.js',
  'variable.other.readwrite',
  'variable.other.readwrite.js',
]

export const COLOR_2 = [
  'comment.block.documentation',
  'comment.line.double-slash',
  'source.go',
  'source.json',
  'source.css',
  'comment',
  'constant.language',
  'constant.other',
  'keyword.control.flow.js',
  'keyword.control.module.js',
  'keyword.operator.accessor',
  'markup.italic',
  'meta.import.js',
  'meta.object-literal.key.js',
  'meta.paragraph.markdown',
  'punctuation.definition.block.js',
  'punctuation.separator.parameter.js',
  'string.quoted.single.js',
  'string.quoted.single.json',
  'support.class.promise.js',
  'support.function',
  'support.function.console.js',
  'support.type.object.console.js',
  'variable.parameter',
]

export const COLOR_3 = [
  'meta.tag.js',
  'variable.language',
  'invalid.UNDERLINE',
  'constant.numeric',
  'meta.brace.square.js',
  'meta.var.expr.js',
  'keyword.control.import.js',
  'keyword.control.from.js',
  'keyword.control.export.js',
  'keyword.control.default.js',
  'support.type.object.module.js',
  'punctuation.definition.parameters.begin.js',
  'punctuation.definition.parameters.end.js',
  'markup.quote',
  'entity.other.attribute-name.js',
  'meta.parameters.js',
  'variable.other.class.js',
  'constant.other.object.key.js',
  'entity.name.function.method',
  'string.quoted.single.js',
  'support.type.property-name.json',
  'variable.other.property.js',
  'entity.name.class.UNDERLINE',
]

export const baseBase = {
  name   : '_Palette',
  type   : 'light',
  colors : {},
}

export const baseData = {
  COLOR_0,
  COLOR_1,
  COLOR_2,
  COLOR_3,
}
